[fmed]
    ua = "Медичний факультет"
    ru = "Медицинский факультет"
    en = "Faculty of Medicine"
    sk = "Lekárska fakulta"

[flaw]
    ua = "Юридичний факультет"
    ru = "Юридический факультет"
    en = "Faculty of Law"
    sk = "Právnická fakulta"

[fphil]
    ua = "Філософський факультет"
    ru = "Философский факультет"
    en = "Faculty of Arts"
    sk = "Filozofická fakulta"

[fns]
    ua = "Факультет природничих наук"
    ru = "Факультет естественных наук"
    en = "Faculty of Natural Sciences"
    sk = "Prírodovedecká fakulta"

[fedu]
    ua = "Педагогічний факультет"
    ru = "Педагогический факультет"
    en = "Faculty of Education"
    sk = "Pedagogická fakulta"

[fpharm]
    ua = "Фармацевтичний факультет"
    ru = "Фармацевтический факультет"
    en = "Faculty of Pharmacy"
    sk = "Farmaceutická fakulta"

[fsport]
    ua = "Факультет фізичного виховання і спорту"
    ru = "Факультет физического воспитания и спорта"
    en = "Faculty of Physical Education and Sport"
    sk = "Fakulta telesnej výchovy a športu"

[jfmed]
    ua = "Єсенієвський медичний факультет"
    ru = "Есениусский медицинский факультет"
    en = "Jessenius Faculty of Medicine"
    sk = "Jesseniova lekárska fakulta"

[fmph]
    ua = "Факультет математики, фізики та інформатики"
    ru = "Факультет математики, физики и информатики"
    en = "Faculty of Mathematics, Physics and Informatics"
    sk = "Fakulta matematiky, fyziky a informatiky"

[frcth]
    ua = "Факультет римо-католицької теології"
    ru = "Факультет римо-католической теологии"
    en = "Faculty of Roman-Catholic Theology"
    sk = "Rímskokatolícka cyrilometodská bohoslovecká fakulta"

[fevth]
    ua = "Євангелічно-лютеранський теологічний факультет"
    ru = "Евангелическо-лютеранский теологический факультет"
    en = "Evangelical Lutheran Theological Faculty"
    sk = "Evanjelická bohoslovecká fakulta"

[fm]
    ua = "Факультет менеджменту"
    ru = "Факультет менеджмента"
    en = "Faculty of Management"
    sk = "Fakulta managementu"

[fses]
    ua = "Факультет соціально-економічних наук"
    ru = "Факультет социально-экономических наук"
    en = "Faculty of Social and Economic Sciences"
    sk = "Fakulta sociálnych a ekonomických vied"
