./new-multilang.sh chapter fmed 
./new-multilang.sh chapter flaw 
./new-multilang.sh chapter fphil 
./new-multilang.sh chapter fns 
./new-multilang.sh chapter fedu 
./new-multilang.sh chapter fpharm 
./new-multilang.sh chapter fsport 
./new-multilang.sh chapter jfmed 
./new-multilang.sh chapter fmph 
./new-multilang.sh chapter frcth 
./new-multilang.sh chapter fevth 
./new-multilang.sh chapter fphil 
./new-multilang.sh chapter fm 
./new-multilang.sh chapter fses 
./new-multilang.sh chapter ubytovanie 
./new-multilang.sh chapter ubytovanie/mlyny 
./new-multilang.sh chapter ubytovanie/druzba
./new-multilang.sh chapter ubytovanie/general
./new-multilang.sh chapter general
./new-multilang.sh default about.md
./new-multilang.sh home _index.md
./new-multilang.sh default faq.md