baseURL = 'https://kamenlabs.github.io/'
theme = 'hugo-theme-relearn'

[params]
  [[params.themeVariant]]
    identifier = 'relearn-light'
    name = 'Light'

  [[params.themeVariant]]
    identifier = 'relearn-dark'
    name = 'Dark'

defaultContentLanguage = 'uk'
defaultContentLanguageInSubdir = true

[languages]
  [languages.uk]
    title = 'Kameň Labs UA'
    contentDir = 'content/ukrainian'
    languageName = 'Українська'
    weight = 10
  [languages.ru]
    title = 'Kameň Labs RU'
    contentDir = 'content/russian'
    languageName = 'Русский'
    weight = 20
  [languages.sk]
    title = 'Kameň Labs SK'
    contentDir = 'content/slovak'
    languageName = 'Slovenský'
    weight = 30
  [languages.en]
    title = 'Kameň Labs'
    contentDir = 'content/english'
    languageName = 'English'
    weight = 40